### ISSUE TITLE
Interested in Changing this to use delegate_to: localhost ?

### ISSUE THREAD

**Issue by larryfast** [f500/ansible-dumpall#4]
As written the code works for individual servers.  But it's possible to get a report of EVERYTHING on the localhost without ever touching the remote servers to generate the report.  If interested I can send a pull request with all the changes. Then we can discuss the implications.

The extensions I've made could also take this from a pure Role to an included playbook. - if desired! - The way I use this to have the following one-liner at the end of all my playbooks:
- include: roles/dumpvars/dumpvars.pb
  instead of 
- host: localhost
  roles:
  - dumpvars

Two things are needed
1. use delegate_to: localhost.  
2. to get variables for all hosts you need a bit of extra magic. See below.

"hostvars": {
{% for key in groups["all"] %}
"{{key}}": {{ hostvars[key] |to_nice_json }}
,
{% endfor %}

**Comment by ramondelafuente** [comment]
Sorry for the delay. Sure, I'm interested, just send a PR over and I'll take a look.

**Comment by larryfast** [comment]
Hi Ramon,
I'm a newbie and this is my first attempt to push code to github and it's failing. I cloned the repo, created a branch, committed my changes and then the git push attempt fails.  Here's the command I used:
git push --set-upstream origin generate_in_localhost
  remote: Permission to f500/ansible-dumpall.git denied to larryfast.

I also tried to create a branch via the github web interface. This also seems to be blocked.  

Do you need to grant me permission to write to your project?  Or is it something else?

**Comment by ramondelafuente** [comment]
Ah ok :-) Here goes: 

You're trying to put the changes directly in my repository. But you don't have the privileges to do that, as you've found out. The way to move forward is not to make a clone of _my_ repo, but to create a _fork_, so that you have your own copy of the repo to make changes on!

After you made the changes and pushed them (to your repo, where you have all the privileges), you can create a _pull request_ that in essence, offers your changes back to me so I can decide if I want them in my repo.

So normally you would:

- Fork a repo. The _fork_ button is on your top-right in GitHub, next to the name of the repository.
- You clone your own repo locally.
- You make a branch, just like you did, and do the changes.
- You push the changes.
- Visit GitHub and create a Pull Request.

In your case, because you have a repo and branch with the correct changes, you could also:

- Fork the repo
- Set your repo as the origin of the local copy `git remote add origin [your repo url]`
- Push the changes in your branch
- Visit GitHub and create a Pull Request.

I hop this helps, and makes the process somewhat more clear!

**Comment by ssbarnea** [comment]
Any updates on this? I would find extremely helpful to dump all these on the controller host.

**Comment by larryfast** [comment]
Hi ssbarnea.  We decided my variant on this tool implements a different behaviour model.  So it was never merged. If you want to dump onto the Ansible host, you can look at my code here: https://github.com/larryfast/ansible-dumpall

**Comment by ramondelafuente** [comment]
This is the conversation, for future reference: #5
